### ISSUE TITLE
Crafting with Socket Gems

### ISSUE THREAD

**Issue by Gelatinman** [Nunnery/MythicDrops#193]
Before you close this and send me here https://github.com/Nunnery/MythicDrops/commit/7a9dd29a98ed4896c2c310a3e242ca93828d758d

Could you please explain how to actually fix the problem. From what I see I don't know how that code could help unless its been added to the latest downloadable version. My players can still craft things out of socket gems and socket sticks and I haven't got the slightest clue how to fix it. Your plugin is fantastic and i would love to continue using it.

I'm using latest craftbukkit and your latest version of Mythicdrops

all configurations are set to default for mythicdrops

Only other plugins i'm using
- Essentials
- World Edit
- World Guard
- lore
- GriefPrevention
- Permissionsex
- NoCheatPlus
- ProtocolLib
- Fishing Plus

I have no plugins that would mess with crafting recipes.

**Comment by UltraFaceguy** [comment]
Woah major mind screw going on right here. Turns out I visited this page exactly one year later, and didn't notice the 2014 and I be like WHAAAAAAAAAAAAAAAAAAAAAT
