### ISSUE TITLE
bonusLore not working

### ISSUE THREAD

**Issue by Boosik** [Nunnery/MythicDrops#227]
bonusLore just does not do anything :(.

lore:
  minimumBonusLore: 2
  maximumBonusLore: 4
  baseLore:
  - '&6Jen ti nejlepší mohou nosit tuto věč!'
  bonusLore:
  - '&c+40% Kriticke poskozeni'
  - '&c+4 Armor'
  - '&c+4 Sila zbrane'
  - '&c+8% Sance na kriticky zasah'
  - '&c+4 Sila luku'
  - '&c+8% Uhybani'
  - '&c+4 Zdravi'

With this setup all items have only '&6Jen ti nejlepší mohou nosit tuto věč!' lore :(

**Comment by Drehverschluss** [comment]
lore:
  minimumBonusLore: 0
  maximumBonusLore: 2
  baseLore:
  - '&7Tier: %tiername%'
  - '&7Level: 1'
  bonusLore:
  - '&fTest1'
  - '&fTest2'

**Comment by Nunnery** [comment]
@Drehverschluss is correct. You have to add the "%bonuslore%" into the config.yml.
