### ISSUE TITLE
No Drop from Unidentified Items

### ISSUE THREAD

**Issue by Drehverschluss** [Nunnery/MythicDrops#230]
Hello dear MythicDrops coder.

I found a Issue. Doesnt matter what i am doing im not able to get the "chanceToBeIdentified: 0.001" to work. They are always identified.

Or do i make something wrong?

**Comment by Nunnery** [comment]
Chance to be identified is considered when identifying items. When you use an identity tome, the "chanceToBeIdentified" is used to calculate if the item is of the given tier.

**Comment by Drehverschluss** [comment]
ahhh ok that explains alot.

But anyway that in the normal Config.
drops:
  item-chance: 0.0
  socket-gem-chance: 0.2
  identity-tome-chance: 0.2
  custom-item-chance: 0.0
  unidentified-item-chance: 0.8
That would consider to drop only unidentified items right? But thats not working though :(

**Comment by Drehverschluss** [comment]
I tryed now to sett the item-chance to 0.2 but than i get this msg when the mobs shall spawn. http://pastebin.com/EkQgxDpy
