### ISSUE TITLE
Where is the bukkit page?

### ISSUE THREAD

**Issue by gh0ztbuster** [Nunnery/MythicDrops#233]
I can't seem to find the bukkit page or any way to download the compiled plugin.

**Comment by Nunnery** [comment]
No idea. It seems to have been removed.

**Comment by gh0ztbuster** [comment]
Can you get it back?

**Comment by Nunnery** [comment]
We're currently on Spigot. http://www.spigotmc.org/resources/mythicdrops.6114/

**Comment by gh0ztbuster** [comment]
Can you re-add the Bukkit page? It had a lot of information.
