### ISSUE TITLE
No mobs are spawning with MD items, but plugin appears to be loaded and working.

### ISSUE THREAD

**Issue by PsychoNavigator** [Nunnery/MythicDrops#236]
I was using a fork that someone had posted in the bukkit forums for a kinda'ish update for 1.8 (called v5 or other) and that worked fine aside from some errors; however once I saw that this was being officially updated, I nuked the other jar and plugin folder and installed this one.

It's working, shows up in my /pl list as green and I can spawn tier items, but no mobs are generating with MD loot at all.

**Comment by Nunnery** [comment]
Have you tried clearing out the old mobs and testing if absolutely brand new mobs have items?

**Comment by PsychoNavigator** [comment]
Full reinstall with latest jar fixed everything. Thanks for closing this, I'd meant to get to this earlier.
