### ISSUE TITLE
Mobs not spawning with loot

### ISSUE THREAD

**Issue by Toastmeister** [Nunnery/MythicDrops#237]
I decided to add MythicDrops to my server, however none of the mobs are dropping any loot, though I am able to spawn in loot using commands.
The log isn't showing any errors and the server is completely stable.
I tried generating a new world having MythicDrops installed before I started the generating, and that actually worked; mobs were dropping loot and everything was working. However, starting a new world isn't a viable option for me as there has been made too much progress to just let go of.

I have tried making a server-folder where I moved the world-files and the server-properties from the main server, along with all the other files from the folder where mobs actually dropped loot: This however didn't work.
I also tried moving the world-files and the server-properties from the main server and just generating the rest though this didn't work either, so it seems that the problem is world-specific.

If you have a solution or need more information, please notify me. I really like this mod and I'd give my left lung to get it working.

**Comment by Nunnery** [comment]
One solution that I'd try is killing any mobs that already exist on the server using something like WorldEdit's "//butcher" command. One thing that happens is that mobs that don't have an item equipped will not drop items. Any mobs that you kill that existed before you added the plugin will not have any items and thus will not drop anything.

**Comment by Toastmeister** [comment]
Alright, so I installed WorldEdit and tried the butcher command, then went on to kill around 50 skeletons/zombies, though none of them dropped anything. Then I went into unexplored territory and killed about 50 skeleton/zombies there as well, though none of them dropped anything either.

I then realized that the world generation was set to AMPLIFIED, so I made another server also using AMPLIFIED for the world generation setting, and what do you know, none of the mobs on that server dropped anything either. And changing the world generation setting from AMPLIFIED to DEFAULT didn't make a difference.

So now I'm wondering: Is there's any particular reason that the plugin doesn't work with amplified world generation? And am I now stuck with an amplified world that doesn't have any mobs with loot, or is there any change I could make to fix that? Assuming that amplified world generation is the culprit, of course.

**Comment by Nunnery** [comment]
I can't think of a reason that it wouldn't work on an amplified world, but I'll scour the code and get back to you when I can think of something.

**Comment by Nunnery** [comment]
Is the name of the world that you're testing in the config.yml as an enabled world?

**Comment by Toastmeister** [comment]
No, it was indeed not. The name of the world for the main server is "Goes to 11", which was also the name for the other amplified server I tested, because I copied the server.properties file. And I guess that's why no mobs spawned with loot in that world either.

I tried adding the "Goes to 11" world-name to the config.yml, but the config.yml just reset itself to the default state every time I launched the server. The config.yml also changes back to the default state every time I try to change anything else as well, which I guess is also sort of an issue.

The name of the world in server where mobs actually did spawn with loot, was simply "world", so I figured that world-name works by default. So I changed the world-name in the main server to "world" as well (in addition to changing it in the server.properties), and lo and behold, mobs now spawn with loot! Awesome!

So yeah, issue solved, though the name of world had to be changed, and I still can't change anything in the config.yml.

**Comment by Nunnery** [comment]
Have you tried stopping the server, making the changes, and then restarting the server? That seems to fix most of the issues with configuration that most people have.

**Comment by Toastmeister** [comment]
Sorry for the late reply: Yes, and it didn't work, sadly. I even tried making the changes right after re-booting the computer (to make sure no processes were lingering), then launching the server. Still had the same problem.

**Comment by Nunnery** [comment]
One more preliminary question that might help me know where the problem lies: have you made absolutely sure to not touch the version field at the top/bottom of the configuration file? Touching that can mess with the plugin and make it do weird things.

**Comment by Toastmeister** [comment]
Did indeed not touch it. And there isn't really a "top" or "bottom", but rather one long line of text, and some of that text is kinda clumped together.

![image](https://cloud.githubusercontent.com/assets/11032033/7757975/91cffd36-0006-11e5-9730-3a418e1516e6.png)

Could this be the problem? I'm opening the file with Notepad in Windows 7.

**Comment by Nunnery** [comment]
Go acquire a text editor that isn't Notepad, such as [Notepad++] or [Sublime Text]. Open the file with that and then edit the files. Make sure to save you're work after you're done.

[Notepad++]: https://notepad-plus-plus.org/
[Sublime Text]: http://www.sublimetext.com/

**Comment by Toastmeister** [comment]
Tried changing it with [Brackets](http://brackets.io/) and now it works! Thank you so much for the help; I'll buy you a drink if I ever meet you in real life :smile:

**Comment by Nunnery** [comment]
Glad it worked for you!
