### ISSUE TITLE
The only swords being dropped are wooden socket swords.

### ISSUE THREAD

**Issue by PsychoNavigator** [Nunnery/MythicDrops#238]
There's a running joke on our server whenever this announcement comes up:

"§6[MythicDrops] §Fplayername§A has found a §2Socket Sword (Unique)!"

Something along the lines of, "Hey what's that sword made of?" "Wooden you like to know?"

It is the only item that mobs drop as far as socketable weapons go, period. Nothing else has dropped at all.

Any idea on what I can do to fix this?

**Comment by Nunnery** [comment]
Which version number are you running? Run "/version MythicDrops" to find out for me.

**Comment by PsychoNavigator** [comment]
4.0.1-b5-STABLE

**Comment by Nunnery** [comment]
You may need to change your configuration around a bit. The socket sword is the example custom item and shouldn't actually be left as a real item unless you'd like to keep your running joke going.

Stop your server, tweak your configuration, add more custom items or prevent custom items from spawning, start your server. If you can't do that reliably with your production server, create a local server on your desktop or some such in order to test everything.

**Comment by PsychoNavigator** [comment]
I'm uncertain where to change that exactly. Could you point me in the right direction?

**Comment by Nunnery** [comment]
You can find the custom items in [customItems.yml] in your MythicDrops folder. Alternatively, you can reduce the custom item spawning chances in your [config.yml] by changing ```custom-item-chance``` to ```0.0```.

[customItems.yml]: https://github.com/Nunnery/MythicDrops/blob/master/src/main/resources/customItems.yml
[config.yml]: https://github.com/Nunnery/MythicDrops/blob/master/src/main/resources/config.yml

**Comment by PsychoNavigator** [comment]
Okay, awesome. Am I able to add more than one custom item?

**Comment by Nunnery** [comment]
Most definitely. Just make sure that the key (in that example ```socketsword```) is different for every custom item.

**Comment by PsychoNavigator** [comment]
So like socketsword, socketsword_1, etc?

**Comment by Nunnery** [comment]
Essentially, yes.

**Comment by PsychoNavigator** [comment]
Epic. Thank you, dude.

**Comment by Nunnery** [comment]
Feel free to reopen if it doesn't work.

**Comment by PsychoNavigator** [comment]
Will do!
