### ISSUE TITLE
Add Option to Block Enchantments From Stacking

### ISSUE THREAD

**Issue by gh0ztbuster** [Nunnery/MythicDrops#239]
I love this plugin, but I don't like the stacked enchantments on weapons. For example, it can give a Diamond Sword Bane of Arthropods and Sharpness enchants at the same time. I'm wondering if you can fix this by adding an option to block items from having stacked enchants. I realize that this enhancement might be a bit of a challenge since you will probably have to add some kind of enchantment priority system, but I really think many people will appreciate being able to control weapon enchantments better.

**Comment by Nunnery** [comment]
I'll definitely considering adding something of this nature.

**Comment by gh0ztbuster** [comment]
An additional suggestion. When an enchantment is blocked because it is unsafe or is stacked, can it not count numerically towards the minimumBonusEnchantments and maximumBonusEnchantments.

**Comment by Nunnery** [comment]
Well, if that's implemented, it might actually cause a permanent loop in item creation.

**Comment by gh0ztbuster** [comment]
Hmmm, is there a way to kill the loop? after it runs all possible enchantments?

**Comment by Nunnery** [comment]
Theoretically, yes. I'm not entirely sure what the implementation of the enchantments is, it's been a while since I was last digging around in the item gen code.

**Comment by gh0ztbuster** [comment]
How about after it runs all the options listed in the config?

**Comment by Nunnery** [comment]
Glancing through the item gen code, it actually doesn't count towards the minimum enchantments if it's unsafe. I do have a hardcoded amount of maximum attempts in there that prevents infinite looping.
