### ISSUE TITLE
Using BOLD, ITALIC, and UNDERLINE font on names in the tier files 

### ISSUE THREAD

**Issue by gh0ztbuster** [Nunnery/MythicDrops#241]
I'm wondering if you can add support for BOLD, ITALIC, and UNDERLINE font. If there is some way to do this to specific tiers that I am unaware of, I apologize.

Current name options:
```
displayName: Legendary
displayColor: GOLD
identifierColor: DARK_RED
```

This is what CustomEnchantments does for their enchantment lore formatting:
```
CEnchantmentColor: ITALIC;DARK_RED
```
Plus their description:
```
CEnchantmentColor: ITALIC;DARK_RED - The colors of the Custom Enchantments, multiple colors are seperated by a ';', check the list of colors here.
```

**Comment by gh0ztbuster** [comment]
I guess a simple option could simply be something like this:
```
displayFormat: NONE
```
Options could be NONE, BOLD, ITALIC, or UNDERLINE

**Comment by Nunnery** [comment]
Well, to be honest, I love this idea. I think it has a lot of potential. However, MythicDrops is not the platform that it'll work on. MythicDrops just doesn't have the right setup for this style of system. However, a different project that I'm working on called Spoils is a MythicDrops replacement that is much better in just about every respect. It doesn't have all of the same features yet, but it's something that I'm working on.

**Comment by gh0ztbuster** [comment]
:+1:
