### ISSUE TITLE
% Drop Chance

### ISSUE THREAD

**Issue by Malvagio87** [Nunnery/MythicDrops#243]
Under the main config.yml there is:

drops:
  item-chance: 0.25
  socket-gem-chance: 0.2
  identity-tome-chance: 0.1
  custom-item-chance: 0.1
  unidentified-item-chance: 0.1

and in the creatureSpawning.yml there is:

spawnWithDropChance:
  CREEPER: 1.0
  SKELETON: 1.0
  SPIDER: 1.0
  GIANT: 1.0
  ZOMBIE: 1.0
  GHAST: 1.0
  PIG_ZOMBIE: 1.0
  ENDERMAN: 1.0
  CAVE_SPIDER: 1.0
  SILVERFISH: 1.0
  BLAZE: 1.0
  MAGMA_CUBE: 1.0
  ENDER_DRAGON: 1.0
  WITHER: 1.0
  WITCH: 1.0

Does that mean that by default every mob has 100% chance to drop:
an item 25% of the time?
a socket gem 20% of the time?
an identity tome 10% of the time?
a custom item 10% of the time?
an unidentified item 10% of the time?

If so does that mean if i changed only the creatureSpawning.yml file config for skeleton from 1 to .5 then that would mean out of 100 skeletons 50 of them would then have a chance to drop:
an item 25% of the time?
a socket gem 20% of the time?
an identity tome 10% of the time?
a custom item 10% of the time?
an unidentified item 10% of the time?

Im not sure if my question makes sense to you or not.  If it doesn't i will try to clarify it.

**Comment by Nunnery** [comment]
Essentially, it takes the values from the config.yml and multiplies them against the values from the creatureSpawning.yml. Using the above configuration, a CREEPER has a 0.25 (25%) chance of spawning with an item AT ALL. If it does successfully spawn with an item, it has a 0.1 chance of that item being an identity tome, a 0.1 chance of it being a custom item, a 0.1 chance of it being an unidentified item, and a 0.2 chance of it being a socket gem.

If you wanted CREEPERs to drop twice as frequently while maintaining the rest, you would set the CREEPER value to 2.0. If you wanted to halve the drop rate of the others while maintaining CREEPERs, you'd set everything else to 0.5. It allows you to have more fine-grained control over certain mobs dropping items.

**Comment by Malvagio87** [comment]
Is there a Wiki in regards to this plugin?

**Comment by Nunnery** [comment]
There is not a wiki at the moment, no. That's been planned for a while and just never gotten around to.
