### ISSUE TITLE
Identifying Skill Idea

### ISSUE THREAD

**Issue by Malvagio87** [Nunnery/MythicDrops#249]
Not sure if this would be possible but I believe having the ability to level up your Identifying skill to get better enchants on items would be a cool idea.

**Comment by conetopia** [comment]
Last i checked I thought the enchant via sword for loot 1 /2 /3 worked as magic find.
But here is a non-official spigot version.
https://www.spigotmc.org/resources/mythicdrops.5649/
it should have an actual magic find gem.

**Comment by conetopia** [comment]
I think there was a plugin that contains a Dev enchant kit.
So that you could make lores on items, it was compatible with mythic drops.
Just been so long since ive used it.
