### ISSUE TITLE
Enchantments on customitems

### ISSUE THREAD

**Issue by chulitojaume** [Nunnery/MythicDrops#251]
I don't know how to put an enchantment on the customitems, i tried with the enchantment system of tiers, but nothing. How can i put enchantments on a customitem?

**Comment by KaidaSeren** [comment]
test:
  displayName: '&9test
  lore:
  - test

  spawnOnMonsterWeight: 0.0
  chanceToDropOnMonsterDeath: 0.0
  materialName: DIAMOND
  enchantments:
    DURABILITY: 1


This gives the item Unbreaking 1
