### ISSUE TITLE
Creatures unable to spawn with anything rarer than default

### ISSUE THREAD

**Issue by Toastmeister** [Nunnery/MythicDrops#252]
So I wanted to enable every rarity from every mob in the game, however no mobs drop anything rarer than what they are set to do by default. So for example with endermen, they are by default set to only drop uncommon and rare, and so if the CreatureSpawning.yml is left untouched, that's what they will do.
However, if you also enable them to drop "common", they will do that, though if you enable them to drop epic, and/or exotic, and/or legendary, they won't. In fact, if they are set to only drop those three, they won't drop anything at all! Not even custom items or socket gems.

So I'm wondering if there's anything I can do to change that. Maybe a file I can change or something?

**Comment by Nunnery** [comment]
Stop your server, change the configuration, save it, restart your server. If the issue persists, comment on this issue again.

**Comment by Toastmeister** [comment]
That is what I have been doing. I even tried restarting the entire machine, but alas, the problem persists.

**Comment by Nunnery** [comment]
Can you give me a copy of the debug.log from your MythicDrops directory?

**Comment by Toastmeister** [comment]
![debug](https://cloud.githubusercontent.com/assets/11032033/10710242/306ac868-7a50-11e5-8aab-7715753636ae.png)

Not 100 % sure how to send the file as is, so I just renamed it to png.

**Comment by Nunnery** [comment]
Use http://hastebin.com/ or something similar.

**Comment by Toastmeister** [comment]
Alright, think I managed it this time:

http://hastebin.com/yecagodoza.avrasm

**Comment by Nunnery** [comment]
You only have four tiers loaded at the moment: artisan, common, rare, uncommon

You can find information explaining why here:
```
DEBUG com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin - Loading tiers
INFO com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin - Loading tiers from /tiers/
INFO com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin - MAGENTA is not a valid color
INFO com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin - PURPLE is not a valid color
INFO com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin - ORANGE is not a valid color
```

**Comment by Toastmeister** [comment]
Ah, I see! Thank you, that actually clears things up a lot.
I changed the colours to match Minecraft's colour codes, and now everything works as it should.

**Comment by Nunnery** [comment]
Glad I could help! Let me know if there's anything else.
