### ISSUE TITLE
No list of enchantment names

### ISSUE THREAD

**Issue by Toastmeister** [Nunnery/MythicDrops#254]
I was looking to enable the possibility of having any enchantment in the game on every legendary item (like it was in DiabloDrops (if I remember correctly)), however there is no list or anything of what MythicDrops calls the various enchantments. I noticed that the enchantment for infinity on bows displays in the files as "ARROW_INFINITE", while it displays as "Infinity" on this page:

http://minecraft.gamepedia.com/Enchanting/ID

In the tier.yml file, there is a link to available enchantment names, but the page only throws a 404 error:

http://jd.bukkit.org/dev/apidocs/org/bukkit/enchantments/Enchantment.html

So what I'm wondering: Where can I find a list or something (similar to itemGroups.yml) of what the various enchantments are called? I looked through all the files, but couldn't find anything useful.

**Comment by UltraFaceguy** [comment]
You are correct, you can put any enchantment on anything, but that old enchantment list is out of date - He's an updated one: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html

Usually MD works using the technical term for item materials and enchantments, so offical API documents will be your best bet if you forget one. Here's Materials, just in case! https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

Good luck at making some awesome tiers ;D
