### ISSUE TITLE
I have a question about a add-on Plugin for MythicDrops...

### ISSUE THREAD

**Issue by whymeman96** [Nunnery/MythicDrops#256]
Hello Nunnery. There was something I needed to ask you for a while, but wasn't sure where else. I've been using MythicDrops for a long time now for my MC Server and its been one of the few most balanced and stable plugins I've enjoyed to use. I'm very thankful for that since other similar plugins used in the past conflict or break things in a horrid manner even after the "fixes". One thing I remember is that MythicDrops had a very useful support plugin ItemAttributes, which totally upgrades MythicDrops to a whole different (and enjoyable) level. It saved a lot of headache from going between NBT Editors and other intensive work per item needed to be customized. But, since the "issues" with Bukkit, I noticed that ItemAttributes disappeared without a warning and this left MythicDrops kinda stranded in terms of adding fully custom items in the future as now there's a attribute for horse armor and even more in the upcoming 1.9.

An example of the working config from "customitems.yml" combined with ItemAttributes...

HolySword:
  materialName: IRON_SWORD
  displayName: '&fHoly Sword'
  enchantments:
    DAMAGE_UNDEAD: 5
    DURABILITY: 5
  lore:
  - '&2(Socket)'
  - '&2(Socket)'
  - '&2(Socket)'
  - '&6 +5% Critical Rate'
  - '&6 +17% Critical Damage'
  - '&c +2 Regeneration'
  - '&3 +4 Armor'
  - '&7Find a &2Socket Gem&7 to fill a &2(Socket)'

I still use the ItemAttributes plugin you made with pur3pow3r for MythicDrops and i'm wondering if it was combined with ItemAttributes since the time it disappeared. If not, will there be add-ons like it? I fear as old as this version is, it might not survive the next major update and I won't be able to use it. The last version I have of it is 1.1.0-b50.

**Comment by UltraFaceguy** [comment]
Add me on Skype (superfaceguy) to discuss this (I'm Pur3p0w3r)

**Comment by Nunnery** [comment]
I agree, he's the person to talk to about this at the moment.
