### ISSUE TITLE
no player tag for when you want to use the same command for many people with plugins like coupon codes.

### ISSUE THREAD

**Issue by flyinggoatman** [Nunnery/MythicDrops#258]
A simple $player would fix this.

> md give $player -a 10 -t common

This command would give the items to whatever player inserted the command. I will also try and hit up the dev's on CouponCodes to see if they can do anything. I would have commented on the threads but all the ones I found we're locked.

**Comment by Nunnery** [comment]
That would work with the way that the plugin handles the give command. The only issue would be if CouponCodes or whatever plugin doesn't actually change $player to the name of the player.
