### ISSUE TITLE
1.9 Compatibility - Console Errors (massive)

### ISSUE THREAD

**Issue by adnurmal** [Nunnery/MythicDrops#260]
Greetings,

I am aware that you have not updated this plugin for 1.9, tho a majority of it works, it does so with a console spam price.

[Console - Player being attacked](http://hastebin.com/foyilepoku.avrasm) - This would the list of console spam from an entity attacking a player.

[MyPet Console When Summoned](http://hastebin.com/difohohule.avrasm) - This is the error that is constantly repeated when a player has a pet summoned with the plugin [MyPet](https://www.spigotmc.org/resources/mypet-premium.17566/)

I would also like to point out that if a player holds and item in their off-hand slot (F hotkey by default), and they use a socket gem or an identity tome, it will run the socket / identity event, such as socket the item in the off-hand and place a copy / duplicate item into the hotbar.

**Comment by Drehverschluss** [comment]
I get the same error as you at MyPet but i dont even have this installed. Tryed to look whats causing that error but sadly i cant figure it out.

I hope this plugin gets updated cause there is no Plugin like this out there.

**Comment by Nunnery** [comment]
I'll check it out when I get back to my personal computer this evening.

**Comment by Nunnery** [comment]
Spigot's Maven repository isn't accepting my requests at the moment, will update when able.

**Comment by Nunnery** [comment]
Fixed, tested, released on Spigot.
