### ISSUE TITLE
Unidentified Items

### ISSUE THREAD

**Issue by Drehverschluss** [Nunnery/MythicDrops#261]
Hello there.

I worked alot in the past to try getting unidetified items working. Cause i want every item to be unidentified.
But its a pain because you cannot really define the Tier a Unidetified item will have. Only the other way, but this can cause drop in areas where i dont want such high tier drop.

So please add the option to define the Tier wich a unidentified item will have. Or at least a option for that in your API. Since PhatLoot does an amazing jop with support your plugin. He allready tried it and its possible to select a tier in his GUI for the unid item. But well since every tier can have a chance to be indentified its not working the way most people needs it i think ;)

Hope you can understand what i mean. If not just tell me :)

EDIT: This is maby more clearer.

So basiclly a unidentified Item should Listen to the tier befor you identifie it. So you can define what exactly tier a item will have if it drops unid.
MFG

**Comment by Nunnery** [comment]
You can test this [here](http://maven.tealcubegames.com/content/groups/public/com/tealcube/minecraft/bukkit/mythicdrops/4.0.9-SNAPSHOT/). I made it so that when identifiying an item, it checks the last line of the lore of the item for a tier name. If it finds one, it uses that. If it doesn't, it picks randomly.

**Comment by Drehverschluss** [comment]
So that means I need to setup all tiers as unidentified item? 

So I need to define it in the unidentifiedItem.yml? 

I thought about a easyer way.... Like an section  in the tier.yml what said something like "AlwaysUnidOnDrop:true/false" 

This would make life much easier 😉 
Well I will try your build and see how yours work at.  I'm in work at.

**Comment by Drehverschluss** [comment]
Im now at home and i thought a little bit more about what you ment. Well so you basiclly say that i can write one line into my UnidentifiedItem.yml lore to define the Tier a unidItem will have. But isnt that only give me a option to select 1 tier only?

If so than thats not what i mean.

**Comment by Drehverschluss** [comment]
https://github.com/Codisimus/PhatLoots/issues/27#issuecomment-198210221

**Comment by Nunnery** [comment]
Part of it is that Unidentified Items are only checked based on the name of the item itself. You could therefore just create items that have the same name as the Unidentified Item (color and all) that have the tier in the last line of the lore.

It's a bit more complicated, but the capability is there.

**Comment by Drehverschluss** [comment]
Well awesome job 😆

And the development from PhatLoots will provide an extremely easy way for that. Thanks for keeping up this plug in.

**Comment by Drehverschluss** [comment]
I just would like to ask a last question here.

Since you sai i can make a unid Item as a Tier and let them drop. But how can i change the ItemName cause thats got alöways defined in the standard config by item-display-name-format: '&l%basematerial%' in my case. 

I tryed this setup it it still shows me the Material as name.

http://pastebin.com/LuK4SBua

MFG
