### ISSUE TITLE
Latest update - Aurarunnable console errors

### ISSUE THREAD

**Issue by adnurmal** [Nunnery/MythicDrops#262]
[Console](http://hastebin.com/obecomedix.avrasm)

Item copying from the off-hand when right clicking a socket gem is still present.

Most recent 4.0.8-b2bf179 Mythic Drops version and Most recent release of 1.9 Spigot.

Keep up the good work!

**Comment by Nunnery** [comment]
Will release tomorrow at some point most likely.
