### ISSUE TITLE
[4.0.8-b2bf179] Spamming in console on 1.8.8/9

### ISSUE THREAD

**Issue by JackBarnett2016** [Nunnery/MythicDrops#265]
Spigot Version: git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Mythic Drops Version: 4.0.8-b2bf179

There are two main issues that are occuring, this error constantly spams:
https://pste.me/#/9Sgl3

And when people break blocks (Creeative or Survival):
https://pste.me/#/IvJui

Using an old version worked fine, the version I used is: 4.0.2-58e181c

Just a heads up!

**Comment by Drehverschluss** [comment]
I think that version you ar eusing are only for 1.9

Try this link and download the version 4.0.5
https://github.com/Nunnery/MythicDrops/releases

**Comment by Nunnery** [comment]
The version I uploaded on Spigot is only for 1.9. It was mentioned in the patch notes.

**Comment by JackBarnett2016** [comment]
Thanks for this.
