### ISSUE TITLE
Rclick issue when something in Offhand

### ISSUE THREAD

**Issue by Drehverschluss** [Nunnery/MythicDrops#268]
Made some researches.

I toke the tome to test some ShieldSlot Issues. So its like when you habe nothing in your Shieldhand and you rClick with a Tome it appears like you want to identify a AIR item and you become the "You cannot use that Iden......" text .

Ok than i tried to put a UnidItem in my Offhand and rClick with a Tome again. The Item from the offhand slot appears Identified in my Inventory But the Unidentified Item is still in my OffhandSlot.

So when i put my Identifie Tome in my offhand slot its acting like they want to identfie themself.

Thats probably tha same issue as this guys have https://github.com/Nunnery/MythicDrops/issues/267
I hope you got the issue.

mfg

**Comment by Nunnery** [comment]
Try the new build available [here](http://maven.tealcubegames.com/content/groups/public/com/tealcube/minecraft/bukkit/mythicdrops/4.0.10-SNAPSHOT/).

**Comment by Drehverschluss** [comment]
This seems to be fixed. good job.
