### ISSUE TITLE
Mobs not dropping items

### ISSUE THREAD

**Issue by doitliketyler** [Nunnery/MythicDrops#269]
Hey there. I'm running on Spigot 1.9 and the latest version of the plugin and the mobs are not dropping MythicDrops and I'm getting this error in the console:

http://pastebin.com/qeHG7kn4

Any ideas as to whats going on? Thanks in advance.

**Comment by Nunnery** [comment]
I don't believe you're running the most recent version of Spigot for 1.9. Update Spigot and try it. That should fix the issue.

**Comment by doitliketyler** [comment]
Thats exactly what it was. I updated and everything worked flawlessly with MM and solved a few problems I was seeing with other plugins. I didn't even realize there was a newer version of 1.9 so thanks!

**Comment by Nunnery** [comment]
Not a problem! Let me know if you run into any other issues.
