### ISSUE TITLE
Bonus lore doesn't work

### ISSUE THREAD

**Issue by tara81** [Nunnery/MythicDrops#275]
Still shows the item as SUPER in gold, base lore as "An item only the worthy can hold" (it was the config default) and the bonus lore doesnt show up at all.

super:
  displayName: Super
  displayColor: LIGHT_GREEN
  identifierColor: DARK_RED
  lore:
    baseLore:
    - '&a+2 Health'
    bonusLore:
    - '&3+2% Dodge'

**Comment by tara81** [comment]
Still shows the item as SUPER in gold, base lore as "An item only the worthy can hold" (it was the config default) and the bonus lore doesnt show up at all.

**Comment by Drehverschluss** [comment]
you need to give the item a chance to "become" a bonus lore via 
<code>
  minimumBonusLore: 0
  maximumBonusLore: 1
</code>

This chance ia random...change both to 1 and you will always have a bonus lore.

**Comment by tara81** [comment]
okay so why isn't the base lore working ?

**Comment by Drehverschluss** [comment]
remove the first "super:" line. What does that line mean though?

**Comment by Drehverschluss** [comment]
Wich file are you trying to edit? The customItems.yml ?

**Comment by tara81** [comment]
tiers

**Comment by tara81** [comment]
also can I have 2 tiers with the same display name? like super1 and super2 both have displayname Super?

**Comment by tara81** [comment]
+ health lore doesnt work on weapons so i need to make 2 tiers, 1 for armor, 1 for weapons

**Comment by tara81** [comment]
(lore attributes plugin)

**Comment by Drehverschluss** [comment]
Oh oh i see what you are trying :) i made the same. its alittle tricky to get MYthic drops to work. But i can only recommend another plugin where you can define droptables veryeasy and it support MythicDrops.

Pathloot - http://codisimus.com/phatloots

**Comment by tara81** [comment]
i already have phatloots , It takes a really long time to add everything u want to it

**Comment by Drehverschluss** [comment]
And and long as you make different tier files, all of this could have the same DisplayName but each have other stats for sure

**Comment by tara81** [comment]
Yeah but the base lore doesnt work :/

**Comment by tara81** [comment]
http://pastebin.com/tMHdWJ7A

**Comment by Drehverschluss** [comment]
remove the super in the first line

this is not correct

**Comment by Drehverschluss** [comment]
anch each super 1,2,3,4 must have a own file

**Comment by tara81** [comment]
What ??! Then how does the plugin know what tier it is ?

Look this is the defaults for it , it has a tier name then the display name ...

http://pastebin.com/WAPZdMeG

**Comment by Drehverschluss** [comment]
The tier file should look like this http://pastebin.com/L7GEcpsV

**Comment by Drehverschluss** [comment]
you must have a very old version.

The plugin know the tier by the file name.

**Comment by tara81** [comment]
I downloaded it yesterday LOL it gave me this folder and jar . Is the folder old?

**Comment by Drehverschluss** [comment]
the bad thing is there are 2 different version out on spigot.
https://www.spigotmc.org/resources/mythicdrops.6114/

thats the latest....you got this?

**Comment by tara81** [comment]
yes, okay so, there is a tiers folder too.  Now I am really confused why there is tiers.yml then.. Am i repeating the same thing in both the tiers.yml and the tiers folder ?

**Comment by Drehverschluss** [comment]
al though......this tier file you are looking dowsnt exist anymore.....it was used befor but he splitted all the tiers into sepperate files inside the Tiers folder.

The tiers.yml inside the mainplugin folder doesnt do anything anymore

**Comment by tara81** [comment]
Thank you =) Yes I am editting the wrong file.  The lack of documentation is confusing.

**Comment by Drehverschluss** [comment]
yes as i said...very tricky to get it to work ;)

**Comment by tara81** [comment]
Hey i find that the loot chance for tiers seems to all be the same.  Is this true?

chanceToSpawnOnAMonster: 0.1

**Comment by Drehverschluss** [comment]
Yes thats true.
I would suggest to not use MythicDrop´s lootchance´s.
Instead use Pathloot to set this up. There your can define wich tier should drop.

**Comment by tara81** [comment]
Where is pathloot ? i thought it was phatloot

**Comment by tara81** [comment]
sorry where is pathloot in phatloots and how to i hook it up to work with
mythicdrops?

**Comment by Nunnery** [comment]
@tara81 He means to just use PhatLoots to work with drop chances. I'd have to agree with him. PhatLoots has a much easier configuration for chances than MythicDrops does.
