### ISSUE TITLE
Duplication Glitch With Offhand

### ISSUE THREAD

**Issue by ToXiCHaZe541** [Nunnery/MythicDrops#279]
So when you updated this for 1.9 I do not think you made it check for the off hand because if you put a item with socket slots in your off hand then a socket gem in your hot bar and right click it will duplicate the item in your off hand.

**Comment by Nunnery** [comment]
Try with a version from here: http://maven.tealcubegames.com/content/groups/public/com/tealcube/minecraft/bukkit/mythicdrops/4.0.10-SNAPSHOT/

**Comment by Flashera** [comment]
"When holding an item with a socket in the off hand and a gem in the main hand before combining it causes a duplication of both items. (You get a gemmed item in one hand and unchanged in the other.) When this happens, the normal gem behaviour is nonfunctional and it does not disappear as it should."
(From my own report)

**Comment by Nunnery** [comment]
@Flashera is that with the 4.0.10-SNAPSHOT?

**Comment by Flashera** [comment]
This is from the latest release build.

**Comment by Nunnery** [comment]
@Flashera Try it with one of the builds I linked above and let me know if the issue persists.

**Comment by ToXiCHaZe541** [comment]
@Nunnery I tried one of the snapshot builds and the problem is fixed. It just makes using socket gems on an item in the off hand not work and forces you to do it through your hot bar which I like.

**Comment by Nunnery** [comment]
@Flashera any updates? If not, I'll close the ticket.

**Comment by Drehverschluss** [comment]
Well socket gems should defnetly work on items in offhand.

What about shields with socket? So this sickets should never works? Defenetly  a NO from my side. But sry this cant be closed on my mind.

**Comment by Nunnery** [comment]
@Drehverschluss, socket gem effects do still apply from the offhand item. What we're mentioning here is that you can't insert a socket gem into an item in your offhand, it has to be in your main hand to have a socket gem added.

**Comment by Drehverschluss** [comment]
@Nunnery ohhh allready. than i mussunderstood this situation. Well than im fine to forceing player to do it through hot bar.

sry for that
