### ISSUE TITLE
Socket Gem server crash

### ISSUE THREAD

**Issue by Hardclaw** [Nunnery/MythicDrops#282]
Hi there. Serious full server lock up crash here when trying to add a socket gem to a socketed item.

Right clicking the socket gem gives the socketting prompt. Right clicking a socketed item afterwards immediately halts the entire server. All mobs / movement stops and after ~20 seconds the player is kicked ("Timed out").

The server does not respond for approx. 45 seconds, then throws the following error in the console:
[ERROR](http://pastebin.com/8rC51yUE) (read from the bottom up).

The server then remains in this locked state and cannot be accessed, even through Multicraft. After an attempted stop or restart, the server eventually stops only by terminating (killing) it.

My plugin configuration is heavily modified but every other aspect seems to work fine.

Here are a few details of the crash:

![2016-05-21_22 10 27](https://cloud.githubusercontent.com/assets/11392097/15450920/78575e72-1fa3-11e6-906a-830c3ad210bd.png)
Above is an example of the default gem "Spikes I" that I am attempting to use.

My socketGems config looks like this at the "Spikes I" entry:
>  Spikes I:
    type: ARMOR
    potion-effects:
      WITHER:
        intensity: 0.5
        duration: 900
        target: OTHER
        radius: 0
        affectsWielder: false
        affectsTarget: false
    weight: 400
    prefix: Spiked
    lore:
    - '&4Withers enemies for 0.5s when hit'

(indent formatting is correct and unchanged from default in the config file).

![2016-05-21_22 11 19](https://cloud.githubusercontent.com/assets/11392097/15450921/78594d72-1fa3-11e6-8ea0-6e1d17368baf.png)
Above is an example of the item to which I'm trying to apply the socket gem.

I use a separate tier file for each item at each tier. My "commoncap" config looks like this:
>  displayName: Common
displayColor: WHITE
identifierColor: DARK_RED
enchantments:
  safeBaseEnchantments: true
  safeBonusEnchantments: false
  allowHighBaseEnchantments: true
  allowHighBonusEnchantments: true
  baseEnchantments: []
  bonusEnchantments: []
  minimumBonusEnchantments: 0
  maximumBonusEnchantments: 0
lore:
  minimumBonusLore: 0
  maximumBonusLore: 0
  baseLore: []
  bonusLore: []
maximumDurability: 1.0
minimumDurability: 0.1
minimumSockets: 0
maximumSockets: 1
chanceToSpawnOnAMonster: 0.50
chanceToDropOnMonsterDeath: 1.0
chanceToBeIdentified: 1.0
chanceToHaveSockets: 0.1
broadcastOnFind: false
itemTypes:
  allowedGroups:
  ~ cap
  disallowedGroups:
  ~ diamond
  ~ gold
  ~ iron
  ~ chainmail
  allowedIds: []
  disallowedIds: []
optimalDistance: -1
maximumDistance: -1
infiniteDurability: false`

(indent formatting is correct. Items function normally. Hyphens replaced with ~ for github pasting).

In addition, my socketting config looks like this:
>version: 4.0.0-B
options:
  can-drop-socket-gems-on-items: false
  prevent-multiple-name-changes-from-sockets: true
  use-attacker-item-in-hand: true
  use-attacker-armor-equipped: false
  use-defender-item-in-hand: false
  use-defender-armor-equipped: true
  socket-gem-material-ids:
  ~ DIAMOND
  ~ EMERALD
  ~ PRISMARINE_SHARD
  ~ FLINT
items:
  socketted-item-socket: '&8(Socket)'
  socketted-item-lore: []
  socket-name: '&6Socket Gem - %socketgem%'
  socket-lore:
  ~ '&7Right-click whilst holding this gem'
  ~ '&7in your hand to begin socketting.'
  ~ '&8(&8%type%&8)'`

And just to be completely thorough, my MythicDrops "config.yml" looks like this:
>version: 4.0.5
options:
  debug: true
  hooking:
    mcmmo: false
  give-mobs-names: false
  give-all-mobs-names: false
  display-mob-equipment: false
  can-mobs-pick-up-equipment: false
  blank-mob-spawn:
    enabled: false
    skeletons-spawn-without-bow: false
multiworld:
  enabled-worlds:
  ~ Vendia
drops:
  item-chance: 0.6
  socket-gem-chance: 0.0
  identity-tome-chance: 0.0
  custom-item-chance: 0.0
  unidentified-item-chance: 0.0
components:
  creature-spawning-enabled: true
  repairing-enabled: true
  socketting-enabled: true
  identifying-enabled: true
  distance-zones-enabled: false
  populating-enabled: false
display:
  item-display-name-format: '%tierprefix% %tiersuffix%'
  tooltip-format:
  ~ '&8---------------'
  ~ '&7Type: %mythicmaterial%'
  ~ '&7Tier:%tiercolor% %tiername%'
  ~ '%baselore%'
  ~ '%bonuslore%'
  ~ '&8---------------'
  ~ '%socketlore%'
  ~ '%relationlore%'

Any idea what's wrong here? As I mentioned this is a serious crash that requires a forceful stop of the server and I'd rather not force the issue many more times when trying to find out what's wrong..

Thanks for your interest.

**Comment by Nunnery** [comment]
I'll double check when I get home, but one thing to check is make sure you're using dashes instead of tildes in lists.

**Comment by Hardclaw** [comment]
Thanks for checking! I'm certain I am absolutely using dashes - as I mentioned in the post, I changed the dashes to tildes for GitHub as using dashes in a quote makes bullet points.
Also, for the avoidance of doubt, the spaces on each line are incorrect on GitHub. I am certain they are correct in the actual configs.
Thanks again!

**Comment by Nunnery** [comment]
Whoops, didn't see that when I was reading through it.

**Comment by Hardclaw** [comment]
Any update here? I've disabled socketing currently until it's fixed.

Are you able to replicate the error?

**Comment by Nunnery** [comment]
I haven't been able to replicate it yet. Pastebin wasn't working for me when I attempted to view it earlier, but I'll have the ability to check it tonight.

**Comment by Nunnery** [comment]
Try the build located here: [TealCube Jenkins](http://build.tealcubegames.com/job/MythicDrops/branch/development/10/)

**Comment by Hardclaw** [comment]
Thanks, man.

Unfortunately the crash still occurs the same as before :-
Right click Spikes I -> receive socket prompt -> right click socketed "Old Cap" -> server crashes.

Is it something to do with my socketed items showing the socket lore as '**&8**(Socket)' instead of '**&6**(Socket)'? I prefer the sockets to be displayed subtly when unused - grey works great here.

I will try and change the other references to '&8(Socket)' and see if it miraculously changes anything.

**Comment by Hardclaw** [comment]
Okay just checked and even returning all references to '&8(Socket)' back to '&6(Socket) as default doesn't fix this issue. Specifically: '&6(Socket)' - gold - socket lore on the item and gold gem display name. In language.yml I have also made certain that all references to sockets are '&6(Socket)' as default.

It may also be worth mentioning that the effects of socket gems **do** work on items. I can find this out by creating a custom item and applying a gem effect to its lore. It appears therefore that the issue is with the actual process of applying the gem effect to the existing item, as opposed to the gem config being incorrect.

**Comment by Zendrex** [comment]
I am having the same issue here. Sadly you cant do any sort of changes to anything related to socketing, whether its the name, adding text before or after it, etc. It simply just crashes the server.

**Comment by Zendrex** [comment]
UPDATE: I found the source of the crash, if you attempt to remove the input for ```socketted-item-lore:``` with something like [] or '', it will crash the server.
