### ISSUE TITLE
Duplicated Item Bug in Gems in Spigot 1.9.4 (JAVA 8.0)

### ISSUE THREAD

**Issue by Ethon6** [Nunnery/MythicDrops#286]
1. Put an UNIDENTIFIED ITEMS in LEFT HAND (SHIELD PLACE) 
2. Put a IDENTIFIED TOME in RIGHT HAND, 
3. Right Click for RIGHT HAND.
4. And players get duplicated item.

Plz fix it!

**Comment by Nunnery** [comment]
Duplicate issue of #279.
