### ISSUE TITLE
Custom Items

### ISSUE THREAD

**Issue by kerza4655** [Nunnery/MythicDrops#287]
Can anyone explain exactly what these settings are in terms of percentage and drop rate?
  spawnOnMonsterWeight: 100.0
  chanceToDropOnMonsterDeath: 1.0

Thanks!

**Comment by Nunnery** [comment]
Add up the total weights of each item, then divide an individual item's weight by the total weight, and that's the percentage that the item will spawn.

chanceToDropOnMonsterDeath determines how likely the item is to drop if it is given to monster. 1.0 means 100%.

**Comment by kerza4655** [comment]
So the total weight is all of the individual weights added up together? And isn't there also a custom drop rate located in the config.yml... do they stack on each other or something? Also, in this case, if SpawnOnMonsterWeight is equal to 100 and there are 10 items total, does that mean 100/1000 = .1, meaning .1% or 10%?

Thanks!
