### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by SirKillian** [Nunnery/MythicDrops#289]
Hello,

I'm currently using the latest build (from jenkins) on spigot 1.9.4?

As you probably know playing on Hard difficulty makes it so zombies can spawn additional zombies to “help” when damaged. When this "reinforcement zombie" picks up a dropped Mythicdrops item (items,sockets and tomes) and you kill that zombie the item will drop twice. We can not change the Gamerule MobGriefing to false to prevent those "reinforcement zombies" from picking up items because that will cause villagers to stop working properly. We tried to duplicate any other items but it only works for mythicdrops. 

Thanks for your time,
Killian

**Comment by Nunnery** [comment]
Can you post the contents of your configuration files (not tiers) using something like Pastebin or Hastebin?

**Comment by SirKillian** [comment]
this is our config.yml: http://pastebin.com/uLmg6iF5

**Comment by Nunnery** [comment]
Mobs picking up equipment with that config value set to false shouldn't be happening.

**Comment by Nunnery** [comment]
Out of curiosity, which world is this happening in?

**Comment by SirKillian** [comment]
no mob can pick up the items only the "reinforcement zombie".
This is occurring in every world.

**Comment by SirKillian** [comment]
Thanks a lot! 
So far its working perfectly :)
