### ISSUE TITLE
Ecception spawn

### ISSUE THREAD

**Issue by TrueBlank** [Nunnery/MythicDrops#290]
Sorry to bother but my console is spamming me with this [MythicDrops] Task #266648 for MythicDrops v3.1.0-SNAPSHOT-b0-DEFAULT generated an exception
java.lang.NullPointerException how to I fix that.

**Comment by Nunnery** [comment]
Provide me with a copy of the exception or upgrade MythicDrops.

**Comment by TrueBlank** [comment]
We have the newest version the sockets are creating the exception but nothing has been added so far

**Comment by Nunnery** [comment]
I need an exact version number and a copy of the exception.

**Comment by TrueBlank** [comment]
Thanks for the help I fixed the prob
