### ISSUE TITLE
AuraRunnable causing lots of server lag

### ISSUE THREAD

**Issue by SirKillian** [Nunnery/MythicDrops#291]
Hi, our server is getting a few lag spikes here and there and when I did a /timings it told me:

timings 1 : http://prntscr.com/bhg9tn
timings 2: http://prntscr.com/bhmijd
sometimes it uses over 65%

Is there a way to prevent this from causing lag?

**Comment by Nunnery** [comment]
Do you currently use aura gems?

**Comment by SirKillian** [comment]
We are using 2.
This is how its setup in our SocketGems.yml: 
http://prntscr.com/biaw9r

**Comment by Nunnery** [comment]
You're not actually using aura gems, you're using area gems. Not sure why AuraRunnable is taking up so much CPU time, then, since AuraRunnable doesn't pick up on area gems.

**Comment by SirKillian** [comment]
thanks for the help once again :) alth, the most recent download link for build #15 on jenkins is not working for me :/
