### ISSUE TITLE
Custom items?

### ISSUE THREAD

**Issue by ReloadSniper** [Nunnery/MythicDrops#303]
How to add different Dyes, Different Glass panes, etc. Apparently MaterialName: Dye is not valid?

  materialName: DYE_4 (DYE:4 DYE;4)
  displayName: '&7[Material] Lapis lazuli'
  lore:
  - '&7Used in Crafting!'
  - '&7Dropped from Monsters!'
  spawnOnMonsterWeight: 25
  chanceToDropOnMonsterDeath: 1.0
  broadcastOnFind: true

**Comment by Nunnery** [comment]
There isn't currently a way to support multiple dyes or items with extra data like wood. This might be coming in a later version.
