### ISSUE TITLE
Unable to find where to delete default items..?

### ISSUE THREAD

**Issue by Corcustos** [Nunnery/MythicDrops#305]
I'm unable to find where I need to go to delete the default items that mythicdrops spawns. I want to make my own custom common, uncommon, etc items without having pollution of the normal items. I'm going to assume that the fact that I can't find it is just a user error. I'd be surprised if this wasn't possible, after all of this time put into the plugin. Anyways, what I'm wanting to do is delete ALL of the default items and create about 300+ or so of my own. If this isn't possible, then consider this a suggestion. I looked through all of the configs and directories/couldn't find anything, but I'm hoping that I just happened to overlook this feature, or perhaps I'm misunderstanding something. That's all I'm looking for. Thanks.

**Comment by Nunnery** [comment]
Are you looking for handcrafted items or randomly generated tiers?

**Comment by Corcustos** [comment]
I'm looking to remove all of the defaultly generated items and create my own tiers with my own items to each tier.
