### ISSUE TITLE
Error being spammed in console

### ISSUE THREAD

**Issue by Grexis** [Nunnery/MythicDrops#308]
I just installed this plugin and I keep getting this spammed in the console 

> 6:49:43 PM [SEVERE] Could not pass event EntityDeathEvent to MythicDrops v4.0.13-80e7cf0
6:49:43 PM org.bukkit.event.EventException
6:49:43 PM 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit.jar:git-Bukkit-0a645a2]
6:49:43 PM 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:347) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.EntityLiving.die(EntityLiving.java:863) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.EntityZombie.die(EntityZombie.java:561) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.EntityLiving.damageEntity(EntityLiving.java:801) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.EntityMonster.damageEntity(EntityMonster.java:42) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.EntityZombie.damageEntity(EntityZombie.java:167) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.EntityHuman.attack(EntityHuman.java:995) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.EntityPlayer.attack(EntityPlayer.java:1045) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1266) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:52) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:11) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:44 PM 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:45 PM 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_112]
6:49:45 PM 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_112]
6:49:45 PM 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:45 PM 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:670) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:45 PM 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:45 PM 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:45 PM 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534) [craftbukkit.jar:git-Bukkit-0a645a2]
6:49:45 PM 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
6:49:45 PM Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.EntityEquipment.getItemInMainHand()Lorg/bukkit/inventory/ItemStack;
6:49:45 PM 	at com.tealcube.minecraft.bukkit.mythicdrops.spawning.ItemSpawningListener.handleEntityDyingWithGive(ItemSpawningListener.java:345) ~[?:?]
6:49:45 PM 	at com.tealcube.minecraft.bukkit.mythicdrops.spawning.ItemSpawningListener.onEntityDeath(ItemSpawningListener.java:274) ~[?:?]
6:49:45 PM 	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source) ~[?:?]
6:49:45 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
6:49:45 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
6:49:45 PM 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit.jar:git-Bukkit-0a645a2]
6:49:46 PM 	... 23 more

>

**Comment by Nunnery** [comment]
MythicDrops does not support 1.8 since version 4.0.10 at least.
