### ISSUE TITLE
Crashing when trying to socket. +Small extra issue.

### ISSUE THREAD

**Issue by Corcustos** [Nunnery/MythicDrops#310]
I'm not sure why this is happening, but when I'm trying to put a socket on an item the server crashes. The plugin correctly recognizes the socket gems and if they are a tool/armor gem because it gives me the error message when I try to put an armor gem on a tool, but when I try and put a tool gem on a tool, or armor on a piece of armor, the server crashes. It was working fine until I changed the socket gem configuration files and I am unable to find the issue. I also have deleted all of the socket gems and tiers and currently have 1 armor gem, 1 tool gem, and 1 tier. Additionally, I cannot find where to change the color of MD enchantments when applied. I'm wanting to change it from &6 to &7 like normal enchantments, but I can't find where it is. I know I have to be missing it because I doubt something that small would be overlooked. Could someone perhaps guide me in finding it?

Spigot Version: 1.8.9
MythicDrops version: 4.0.2

Crash message: [X](http://pastebin.com/ncR4E98B)
Debug log: [X](http://pastebin.com/CqjjbCwa)
socketGems.yml: [X](http://pastebin.com/w3nGV1LZ)
socketting.yml: [X](http://pastebin.com/Lv9kNvcD)
delirious.yml: [X](http://pastebin.com/qBUvnf5a)

If you need any extra info let me know. Thanks.

**Comment by Corcustos** [comment]
The issue is the socket gem lore I found out. I'm not able to figure out how to completely erase it. Leaving it blank, putting a hashtag before them, and using brackets causes it to crash, but just deleting the message causes a blank space on the item.

**Comment by Nunnery** [comment]
I will look into this when I get home this evening.

**Comment by Corcustos** [comment]
@Nunnery
