### ISSUE TITLE
Spawner disable option not working in Custom Named worlds

### ISSUE THREAD

**Issue by PengBread** [Nunnery/MythicDrops#320]
Disabled spawner, eggs etc in config not working in custom named default and multiverse world "Example: Wild" . Only works for default world named as "world".

https://pastebin.com/zkxsTSvM

Tried a few things like

  above-y:
    world: 0 <- Switch the world to Wild, changed the 255 to 0 and still not working for custom named default world.

**Comment by Nunnery** [comment]
https://pastebin.com/yy9risAe

Use that instead. "wild" becomes another key under the above-y key.

**Comment by PengBread** [comment]
still not working.

**Comment by Nunnery** [comment]
Can you provide a new copy of your configuration, as well as verifying that you've stopped your server, made your changes, and then started your server?

**Comment by Reqs91** [comment]
https://pastebin.com/NWFUm9tG

theres a paste of mine as well have it setup as like yours.... i as well tried different ways and still nothing works im still get MDs from spawners

**Comment by Nunnery** [comment]
The above-y option is only for preventing spawns above a certain y value in a given world. The spawner option not actually preventing spawns is a different issue. Can you confirm that you've stopped your server, made the changes, and started the server again?

**Comment by Reqs91** [comment]
i can confirm that it came spawner :true when i first launched the plugin on the server

**Comment by Reqs91** [comment]
and as well i can confirm i stoped changed and started just now as well

**Comment by Nunnery** [comment]
Can you provide your config.yml as well? Just need to check something in there.

**Comment by Reqs91** [comment]
https://pastebin.com/NWFUm9tG    it was in a later post

**Comment by Nunnery** [comment]
That's the creatureSpawning.yml, I need the config.yml.

**Comment by Reqs91** [comment]
oops one sec

**Comment by Reqs91** [comment]
https://pastebin.com/Jeg4UbWe

**Comment by Nunnery** [comment]
@Reqs91 - Yours is due to having display-mob-equipment set to false. Spigot doesn't provide a way for me to know how a mob was spawned in any event other than the mob spawn event. This means that unfortunately, the spawner/spawnEgg/any other spawn preventions will not work unless display-mob-equipment is set to true.

**Comment by Reqs91** [comment]
ok that makes sense then QQ welp ill just turn it back on 
so false means break prevention
true means fix prevention QQ i hate that but o well :P

**Comment by Nunnery** [comment]
So do I, but it's one of the limitations of Spigot/Minecraft.
