### ISSUE TITLE
fast equip broken with enchanted gear

### ISSUE THREAD

**Issue by jordanwilliams1** [Nunnery/MythicDrops#322]
Players can't fast equip enchanted gear when mythic drops is loaded. Could you do a quick fix for this or add an option in the config to allow people to quick equip enchanted gear? 

Only enchanted gear is effected by this. 

https://i.gyazo.com/42207debbb2a3ff96e7daf6a51243d65.gif

**Comment by Drehverschluss** [comment]
I think thats exactly the reson why it was not possible befor!

**Comment by Nunnery** [comment]
Please provide a copy of your config.yml.

**Comment by Nunnery** [comment]
This one was fixed with the release. Reopen if you still have this issue after updating.
