### ISSUE TITLE
Update for 1.12 (Plugin cannot be enabled)

### ISSUE THREAD

**Issue by FaintingHope** [Nunnery/MythicDrops#324]
Please update the plugin for 1.12 (CraftBukkit version git-Spigot-23b6354-0481ae9 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT).

Please see the error message below provided when the plugin fails to enable. Using MythicDrops 4.1.0-73bc262.

`Console	: [23:32:15 INFO]: [MythicDrops] Enabling MythicDrops v4.1.0-73bc262
Console	: [23:32:15 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Console	: [23:32:15 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
Console	: [23:32:15 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Console	: [23:32:15 ERROR]: Error occurred while enabling MythicDrops v4.1.0-73bc262 (Is it up to date?)
Console	: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
Console	: 	at io.pixeloutlaw.minecraft.spigot.config.VersionedSmartYamlConfiguration.<init>(VersionedSmartYamlConfiguration.java:105) ~[?:?]
Console	: 	at io.pixeloutlaw.minecraft.spigot.config.VersionedSmartYamlConfiguration.<init>(VersionedSmartYamlConfiguration.java:89) ~[?:?]
Console	: 	at com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin.reloadConfigurationFiles(MythicDropsPlugin.java:325) ~[?:?]
Console	: 	at com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin.onEnable(MythicDropsPlugin.java:684) ~[?:?]
Console	: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Comment by Nunnery** [comment]
There's a version that works for 1.12 here: https://artifactory.pixeloutlaw.io/artifactory/maven-snapshots/com/tealcube/minecraft/bukkit/mythicdrops/4.1.2-SNAPSHOT/mythicdrops-4.1.2-20170610.041755-1.jar

**Comment by FaintingHope** [comment]
Thank you Nunnery!
