### ISSUE TITLE
Spawning of Custom Items in MythicDrops

### ISSUE THREAD

**Issue by Piperrainfield** [Nunnery/MythicDrops#349]
I don't know what I've done wrong, I can't get any other item to spawn but the Diamond Sword...

I have them at different spawning, changing every now and again to test, but I only ever see the Diamond ones... And though the percent is low, it always drops.

I'm new to this, but I have tried everything, nothing has worked. I could really use some help, thanks.

**Comment by Nunnery** [comment]
I'd need to see your custom items config.

**Comment by Piperrainfield** [comment]
I have changed it again, but it's still only dropping the last item, it's the iron sword now.


![customitems](https://user-images.githubusercontent.com/38999519/39750008-7abbd3e4-52f7-11e8-8882-b69a2c489991.png)

**Comment by Piperrainfield** [comment]
It's probably something very simple that I'm missing. xD

**Comment by Nunnery** [comment]
You need to change the name from socketsword to something unique for each custom item.
