### ISSUE TITLE
Wither Boss Item Drop

### ISSUE THREAD

**Issue by SirGoldman-git** [Nunnery/MythicDrops#353]
With the default configuration wither bosses do not drop items, how can I solve this?

I also tested it on villagers, they don't drop anything, turned egg spawn on true, spawned over a 100 with no drops, spawn two zombie and got a drop.

Haven't tested the ender dragon yet but that's probably not working as well.

Config I made for testing: https://pastebin.com/3qdbMtEe

**Comment by SirGoldman-git** [comment]
Remove this please, I resolved it.

**Comment by Blackyvk** [comment]
@SirGoldman-git can you let me know how you did it for wither and dragon?
