### ISSUE TITLE
Adding a Tier to a custom item

### ISSUE THREAD

**Issue by SavHai** [Nunnery/MythicDrops#354]
im really awful at coding, but i own a minecraft server and i want to make my highest tier items part of the drop table as well, but all of the items are custom. how would i implement a tier to them to where it would show on the custom items, and drop from mobs. thanks!

**Comment by Nunnery** [comment]
Custom items can't have tiers. You can put some sort of display value in the lore to make it look like they have tiers, but they can't/won't be treated like they have tiers.
