### ISSUE TITLE
Socket Gem Enchantments Not Working

### ISSUE THREAD

**Issue by Twiistrz** [Nunnery/MythicDrops#358]
https://hastebin.com/elufumagow.bash

Enchantments seems not working, i test the mending

**Comment by Twiistrz** [comment]
![image](https://user-images.githubusercontent.com/25744238/45918298-5807d100-beb7-11e8-9ac5-3f0f17f81424.png)

**Comment by Nunnery** [comment]
You need a space between the enchantment name and the number.
